paths:
  raw_data: "./data/raw_data/"
  processed_data: "./data/processed_data/"
  models: "./artifacts/models/"
hyperparameters:
  model:
    n_estimators: 100
    max_depth: 5
  train_test_split:
    test_size: 0.2
